# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: hosts
  become: yes

  tasks:

- name: Call Roles
  hosts: hosts
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
