# Playbook to call multiple roles to configure systems
- name: Configure sysems
  hosts: 192.168.15.131
  become: yes

  tasks:

- name: Call Roles
  hosts: 192.168.15.132
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
